### ISSUE TITLE
Option for more compact item grid

### ISSUE THREAD

**Issue by Simn** [GeminiQvQ/LTTPMapTracker#2]
The current separation of Items, Utility and Equipment is nice, but it also wastes a bit of space. It would be nice if there was an option to merge these together. Ideally, one could even resize that window.

The reason for this is that it's easier to integrate a merged view into a stream layout.

**Comment by GeminiQvQ** [comment]
This is currently possible by simply editing the layout file.

**Comment by Simn** [comment]
Ah, perfect!
